-- Aligns ingredient inStore flags with what the Choo Foodstore actually carries.
-- Rule: fresh meat, seafood and non-Asian basics (plain water, table salt/sugar,
-- olive oil, ketchup, peanut butter, honey, fresh herbs grown locally) stay
-- inStore=false. Everything else we stock (Asian sauces, pastes, spices,
-- noodles, rice, dried/preserved goods, frozen items, Asian fresh produce and
-- aromatics like garlic/ginger/scallions/onion/carrot/cucumber) flips to
-- inStore=true with an appropriate aisle.
-- Each UPDATE overwrites ingredients_json for a (recipe_id, locale) row.

-- homepage-mapo (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"400g silken tofu","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Doubanjiang (broad-bean paste)","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tsp Sichuan peppercorns","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"150g ground pork","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 scallions","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Garlic + ginger","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Light soy sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Cornstarch slurry","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-mapo' AND locale = 'en';

-- homepage-dandan (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"200g wheat noodles","amount":"","unit":"","note":"","aisle":"Noodles","inStore":true},{"name":"2 tbsp Chinese sesame paste","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"2 tbsp chili crisp / chili oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tbsp Chinkiang black vinegar","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tbsp light soy sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sui mi ya cai (preserved mustard)","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"100g ground pork","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Scallions","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true}]' WHERE recipe_id = 'homepage-dandan' AND locale = 'en';

-- homepage-garlic-bok-choy (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"4 heads baby bok choy","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"6 dried shiitake","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Vegetarian oyster (mushroom) sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tbsp Shaoxing wine","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"4 cloves garlic","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Cornstarch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sesame oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-garlic-bok-choy' AND locale = 'en';

-- homepage-fried-rice (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"400g day-old jasmine rice","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"3 eggs","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"4 scallions","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Light soy sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"White pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"Sesame oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Neutral oil","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-fried-rice' AND locale = 'en';

-- homepage-crispy-chili-beef (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"400g beef fillet","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 1/2 tbsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"2 tbsp cooking oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tsp sesame seeds","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Marinade: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 2 tbsp Lee Kum Kee Premium Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 2 tbsp Lee Kum Kee Seasoned Rice Vinegar","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Chiu Chow Chili Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 5 tbsp water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Sauce: 1/2 tbsp sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Sauce: 1/2 tbsp cooking wine","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 1 tbsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-crispy-chili-beef' AND locale = 'en';

-- homepage-spicy-eggplant-salad (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"2 eggplants, trimmed and cut into 5 cm strips","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 tbsp sesame seeds","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"2 tbsp oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"3 garlic cloves, crushed","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 spring onion, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 2 tbsp Lee Kum Kee soy sauce with shallot aroma","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: Lee Kum Kee Red Ma-La Chili Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-spicy-eggplant-salad' AND locale = 'en';

-- homepage-garlic-prawns-glass-noodles (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"12-15 tiger prawns with shell","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 nest vermicelli glass noodles","amount":"","unit":"","note":"","aisle":"Noodles","inStore":true},{"name":"2 tbsp vegetable oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 garlic cloves, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 spring onion, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 1/2 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1/2 tbsp Lee Kum Kee Premium Light Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp Lee Kum Kee Pure Sesame Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-garlic-prawns-glass-noodles' AND locale = 'en';

-- homepage-honey-lime-soy-chicken (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"500g chicken thigh fillets","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 handful coriander or spring onions, chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Marinade: 2 tbsp Lee Kum Kee Premium Light Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Marinade: 2 tbsp honey","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 2 tbsp fresh lime juice","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 2 garlic cloves, crushed","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Marinade: 1/2 tsp ground black pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true}]' WHERE recipe_id = 'homepage-honey-lime-soy-chicken' AND locale = 'en';

-- homepage-lucky-cabbage-parcels (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"300g minced pork","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Chinese cabbage leaves","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"40g water chestnuts, finely diced","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 carrot, finely diced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Marinade: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Marinade: 1 tbsp Lee Kum Kee Premium Light Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Marinade: 1 tbsp Lee Kum Kee Pure Sesame Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Marinade: 1 tsp sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 1 tsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Marinade: 1 tsp water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 1 tsp ground white pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"Sauce: 2 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp Lee Kum Kee Pure Sesame Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 2 tbsp water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Sauce: 1 tsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-lucky-cabbage-parcels' AND locale = 'en';

-- homepage-steamed-fish-slices (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"250g sea bass fillet","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"10 soft tofu cubes","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1/2 pinch salt","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tsp Lee Kum Kee Premium Mushroom Seasoning Powder","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 pinch ground white pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"1 tsp water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 bunch pak choi, thinly sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"2 spring onions, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Black Bean Garlic Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Sauce: 1 tsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 1 tbsp water","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-steamed-fish-slices' AND locale = 'en';

-- homepage-harvest-vegetable-pan (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"1 small can sweet corn, drained","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Carrots, diced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Frozen peas","amount":"","unit":"","note":"","aisle":"Freezer","inStore":true},{"name":"Pine nuts","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 tsp cooking oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Seasoning: 1 tbsp Lee Kum Kee Premium Mushroom Seasoning Powder","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Seasoning: 1 tsp Lee Kum Kee Pure Sesame Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Salt, optional","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-harvest-vegetable-pan' AND locale = 'en';

-- homepage-tofu-salad (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"200g firm tofu, drained and diced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 cucumber, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"4-6 lettuce leaves, torn into bite-sized pieces","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200g cherry tomatoes, halved","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Dressing: 3 tbsp Lee Kum Kee Roasted Sesame Dressing","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-tofu-salad' AND locale = 'en';

-- homepage-vietnamese-prawn-mango-rolls (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"8 pieces Vietnamese rice paper","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"16 cooked king prawns","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"100g ripe mango, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"80g cucumber, julienned","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"80g mild lettuce","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"16 mint leaves","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 red chili, julienned, optional","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Dip: 2 tbsp Lee Kum Kee Seasoned Rice Vinegar","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Dip: 1 tbsp Lee Kum Kee Premium Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Dip: 1 tsp Lee Kum Kee Pure Sesame Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Dip: 1 tsp honey","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-vietnamese-prawn-mango-rolls' AND locale = 'en';

-- homepage-poke-bowl (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"250g cooked rice","amount":"","unit":"","note":"","aisle":"Rice","inStore":true},{"name":"200g raw salmon, sashimi quality, diced","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 tbsp edamame, blanched","amount":"","unit":"","note":"","aisle":"Freezer","inStore":true},{"name":"1 small cucumber, cut into sticks","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1/2 carrot, grated","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1/2 avocado, diced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"2 tbsp kimchi, optional","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 1 spring onion, finely sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Chilli Garlic Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp Lee Kum Kee Dumpling Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp honey","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Garnish: 1 tsp toasted sesame seeds","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Garnish: 2 pieces toasted nori","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-poke-bowl' AND locale = 'en';

-- homepage-noodle-salad-chicken (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"300g cooked egg noodles","amount":"","unit":"","note":"","aisle":"Noodles","inStore":true},{"name":"1 medium carrot, julienned","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"100g bean sprouts, blanched","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 cucumber, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"400g cooked chicken, shredded","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"4 tbsp Lee Kum Kee Peanut Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-noodle-salad-chicken' AND locale = 'en';

-- homepage-wasabi-prawns-asparagus (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"180g raw peeled king prawns","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"110g thin green asparagus, cut into 4 cm pieces","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 tbsp light olive oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tbsp Lee Kum Kee Sesame Dressing with Wasabi Aroma","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Garnish: lime wedges","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-wasabi-prawns-asparagus' AND locale = 'en';

-- homepage-cold-mixed-vegetables (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"200g lotus root, thinly sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"20g red onion, thinly sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"20g yellow or red bell pepper, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"20g carrot, julienned","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Sauce: 1 tbsp Lee Kum Kee Premium Mushroom Seasoning Powder","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 2 tsp Lee Kum Kee Premium Light Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Sauce: 1 tsp lemon juice","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-cold-mixed-vegetables' AND locale = 'en';

-- homepage-tom-yum-chicken-spaghetti (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"350g chicken breast, cut into small pieces","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"400g spaghetti","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 onion, grated","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"15 fresh basil leaves, torn","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 pinch ground black pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"1 tbsp oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 1 tbsp Lee Kum Kee Tom Yum Bouillon","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 2 tbsp Lee Kum Kee Tom Yum Bouillon","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 2 tbsp coconut milk or water","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Sauce: 4 tbsp spaghetti cooking water","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-tom-yum-chicken-spaghetti' AND locale = 'en';

-- homepage-mushroom-asparagus-risotto (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"300g risotto rice","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"200g mushrooms, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"120g asparagus, peeled and halved","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 onion, chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"50g vegan parmesan, grated","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tbsp mixed herbs","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2 tbsp olive oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 pinch freshly ground black pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"Broth: 1 packet Lee Kum Kee Umami Mushroom Bouillon","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Broth: 1.2 liters hot water","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-mushroom-asparagus-risotto' AND locale = 'en';

-- homepage-seafood-rice-soup (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"250g mixed seafood, for example prawns, clams, squid or scallops","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 bowls cooked rice","amount":"","unit":"","note":"","aisle":"Rice","inStore":true},{"name":"1 packet Lee Kum Kee Seafood Bouillon","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 liter hot water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Chopped spring onion and coriander, optional","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Optional dip: 2 tbsp Lee Kum Kee Premium Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Optional dip: 1 tsp Lee Kum Kee Seasoned Rice Vinegar","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Optional dip: 1 tsp Lee Kum Kee Chiu Chow Chili Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true}]' WHERE recipe_id = 'homepage-seafood-rice-soup' AND locale = 'en';

-- homepage-spicy-fish-soup (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"400g sea bass or cod fillet","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"100g enoki mushrooms","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"3 tomatoes","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Coriander for garnish, optional","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Marinade: 1 egg","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Marinade: 2 tbsp corn starch","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Marinade: 1 tsp salt","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 1 tsp cooking wine","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Marinade: 1/2 tsp ground white pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"Bouillon: 1 packet Lee Kum Kee Spicy Bouillon Sichuan Style","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Bouillon: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Bouillon: 1 tsp sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Bouillon: 1.2 liters hot water","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-spicy-fish-soup' AND locale = 'en';

-- homepage-satay-rice-noodle-soup (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"400g cooked rice noodles or 200g raw rice noodles","amount":"","unit":"","note":"","aisle":"Noodles","inStore":true},{"name":"200g chicken breast, cut into pieces","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"60g carrot, grated","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"40g onion, grated","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"60g baby corn, halved","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 tbsp oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"Marinade: 1 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"Bouillon: 1 packet Lee Kum Kee Satay Bouillon","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"Bouillon: 1.2 liters hot water","amount":"","unit":"","note":"","aisle":"","inStore":false}]' WHERE recipe_id = 'homepage-satay-rice-noodle-soup' AND locale = 'en';

-- homepage-fresh-herb-dip (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"2 tbsp Lee Kum Kee Premium Oyster Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"2 tbsp ketchup","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tbsp fresh tomato, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"Fresh herbs, for example coriander, spring onion or basil","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true}]' WHERE recipe_id = 'homepage-fresh-herb-dip' AND locale = 'en';

-- homepage-sesame-peanut-sauce (EN)
UPDATE recipe_translations SET ingredients_json = '[{"name":"2 tbsp Lee Kum Kee Sweet Soy Sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tsp Lee Kum Kee Chiu Chow Chili Oil","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tbsp peanut oil","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tsp sesame seeds","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"3 tbsp soup or hot water","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2 tbsp spring onion and coriander, finely chopped","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true}]' WHERE recipe_id = 'homepage-sesame-peanut-sauce' AND locale = 'en';

-- homepage-mapo-tofu (EN/DE/ZH) — flip aromatics to in-store, keep meat & stock out
UPDATE recipe_translations SET ingredients_json = '[{"name":"500g soft tofu","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200g ground pork or beef","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"3 tbsp peanut oil","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 tsp Sichuan peppercorns","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2 tbsp doubanjiang (broad-bean chili paste)","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tbsp douchi (fermented black beans), rinsed","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 tbsp Sichuan chili powder","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"15g ginger, minced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"4 garlic cloves, minced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"240ml chicken or vegetable stock","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 tbsp light soy sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 tsp sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1/2 tsp ground white pepper","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2 spring onions, sliced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 tbsp cornstarch + 2 tbsp water (slurry)","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-mapo-tofu' AND locale = 'en';

UPDATE recipe_translations SET ingredients_json = '[{"name":"500g Seidentofu","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200g Hackfleisch (Schwein oder Rind)","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"3 EL Erdnussöl","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 TL Sichuan-Pfeffer","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2 EL Doubanjiang (scharfe Bohnenpaste)","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 EL Douchi (fermentierte schwarze Bohnen), abgespült","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1 EL Sichuan-Chilipulver","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"15g Ingwer, fein gehackt","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"4 Knoblauchzehen, fein gehackt","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"240ml Hühner- oder Gemüsebrühe","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1 EL helle Sojasauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1 TL Zucker","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1/2 TL weißer Pfeffer, gemahlen","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2 Frühlingszwiebeln, in Ringe geschnitten","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1 EL Speisestärke + 2 EL Wasser","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-mapo-tofu' AND locale = 'de';

UPDATE recipe_translations SET ingredients_json = '[{"name":"500克 嫩豆腐","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200克 猪肉末或牛肉末","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"3汤匙 花生油","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1茶匙 花椒","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2汤匙 豆瓣酱","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1汤匙 豆豉，冲洗","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"1汤匙 四川辣椒粉","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"15克 姜，切末","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"4瓣 大蒜，切末","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"240毫升 鸡汤或蔬菜汤","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1汤匙 生抽","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"1茶匙 糖","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"1/2茶匙 白胡椒粉","amount":"","unit":"","note":"","aisle":"Spices","inStore":true},{"name":"2根 葱，切段","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"1汤匙 玉米淀粉 + 2汤匙 水","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true}]' WHERE recipe_id = 'homepage-mapo-tofu' AND locale = 'zh';

-- homepage-kimchi (EN/DE/ZH) — only fresh meat would be out; this recipe has no
-- meat, so napa cabbage, Korean radish, garlic, ginger, scallions, onion,
-- carrot all flip to in-store. Plain water + table salt + sugar stay false.
UPDATE recipe_translations SET ingredients_json = '[{"name":"2kg napa cabbage (about 1 large head)","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200g coarse sea salt","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2L cold water (for brining)","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"500ml water (for the rice porridge)","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"35g sweet rice flour","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"50g sugar","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"150g Korean radish (mu), julienned","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"100g carrot, julienned","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"50g onion, finely grated","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"6 spring onions, cut into 4 cm pieces","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"14 garlic cloves (about 40g), minced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"15g ginger, minced","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"80ml fish sauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"30g salted shrimp (saeujeot), finely chopped","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"100g Korean red pepper flakes (gochugaru)","amount":"","unit":"","note":"","aisle":"Spices","inStore":true}]' WHERE recipe_id = 'homepage-kimchi' AND locale = 'en';

UPDATE recipe_translations SET ingredients_json = '[{"name":"2kg Chinakohl (ca. 1 großer Kopf)","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200g grobes Meersalz","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2L kaltes Wasser (zum Pökeln)","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"500ml Wasser (für den Reisbrei)","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"35g Klebreismehl","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"50g Zucker","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"150g koreanischer Rettich (Mu), in Streifen","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"100g Karotte, in Streifen","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"50g Zwiebel, fein gerieben","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"6 Frühlingszwiebeln, in 4 cm Stücken","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"14 Knoblauchzehen (ca. 40g), fein gehackt","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"15g Ingwer, fein gehackt","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"80ml Fischsauce","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"30g Salzgarnelen (Saeujeot), fein gehackt","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"100g koreanische Chiliflocken (Gochugaru)","amount":"","unit":"","note":"","aisle":"Spices","inStore":true}]' WHERE recipe_id = 'homepage-kimchi' AND locale = 'de';

UPDATE recipe_translations SET ingredients_json = '[{"name":"2公斤 大白菜（约 1 颗大的）","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"200克 粗海盐","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"2升 冷水（用于腌制）","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"500毫升 水（用于米糊）","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"35克 糯米粉","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"50克 糖","amount":"","unit":"","note":"","aisle":"","inStore":false},{"name":"150克 韩国白萝卜，切丝","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"100克 胡萝卜，切丝","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"50克 洋葱，磨碎","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"6根 葱，切 4 厘米段","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"14瓣 大蒜（约 40 克），切末","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"15克 姜，切末","amount":"","unit":"","note":"","aisle":"Fresh / fridge","inStore":true},{"name":"80毫升 鱼露","amount":"","unit":"","note":"","aisle":"Sauces","inStore":true},{"name":"30克 韩式虾酱（saeujeot），切碎","amount":"","unit":"","note":"","aisle":"Pantry","inStore":true},{"name":"100克 韩国辣椒粉（gochugaru）","amount":"","unit":"","note":"","aisle":"Spices","inStore":true}]' WHERE recipe_id = 'homepage-kimchi' AND locale = 'zh';
